# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json
services:
  agent:
    image: ghcr.io/soramitsukhmer-lab/sorakhrun-consul-agent:latest
    environment:
      CONSUL_ZEROCONFIG: "true"
    hostname: "{{.Node.Hostname}}"
    networks:
      host:
    volumes:
      - data:/consul/data
    deploy:
      mode: global
      restart_policy:
        condition: any
volumes:
  data:
networks:
  host:
    name: host
    external: true
