name: consul
services:
  agent:
    image: ghcr.io/soramitsukhmer-lab/sorakhrun-consul-agent:latest
    container_name: agent
    restart: unless-stopped
    environment:
      CONSUL_ZEROCONFIG: "true"
    hostname: $HOSTNAME
    network_mode: host
    volumes:
      - data:/consul/data
volumes:
  data:
